### ISSUE TITLE
About the project (into)

### ISSUE THREAD

**Issue by ellaklara** [DH2413-AGI/Lightenize#54]
Goal and motivation
The tech behind
Look at Proposal presentation for inspo

300-400 words (approx)

**Comment by AdamJonsson** [comment]
Lightenizer is an augmented reality puzzle game that uses the additive color system as its main game mechanic. It consists of only two types of elements, a light sensor that needs to have the correct colored light on it, and light sources that shine a specific color. The goal is to move the light sources around, such that every light sensor has the correct light shined on them. However, the catch is that some light sensors require a color that is not directly shined from any light source. In these cases, the user needs to combine different colored lights to create new colors, thus learning the additive color system by exploration.

Another important goal other than learning the additive colors system was that the experience was engaging for a younger audience.  Augmented reality was therefore used for both its flexibility in viewing the world from a mobile device, and also that the user can intuitively move and rotate the light sources. AR also reduce the sedentary behavior while playing and is instead encourage movements which we found the heightened the users engengement.
